
#--------------BASICS--------------#

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

#--BATTERY
# [[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
# threshold = 100
# style = "bold red"

#--CHARACTER MODULE
[character]
success_symbol = "[ïŸ](bold green)"
error_symbol   = "[ïŸ](red)"
vicmd_symbol   = "[ïŸ](yellow)"

#--CMD DURATION
[cmd_duration]
show_notifications=true
style = "bold red"
format = " [$duration]($style) "

#--------------LANGUAGES--------------#

[python]
symbol = ""

[rust]
symbol = ""
style = ""

#--------------GIT STUFF--------------#
[git_branch]
symbol = "îœ¥ "

[git_status]
conflicted = "ï²…(red)"
ahead = "[ï¥¢${count}](blue) "
behind = "[ï„ª ${count}](bold red) "
untracked = "[ï„¨ ${count}](yellow) "
stashed = "[ğŸ“¦ ](purple) "
modified = "[ï•© ${count}](blue) "
staged = "[ğŸ—ƒï¸ ${count}](orange) "
renamed = "[ï®· ${count}](bold red) "
deleted = "[ï‡¸ ${count}](red) "


#--------------RANDOM--------------#

[custom.vid]
description = "to show vlc icon to folders containing vid files"
shell = ['bash']
command = "echo ï©»"
style = "#D08770"
extensions = ["mp4","mkv","webm"]
format = "[$output]($style)"
